.idea/gwachaepah_practice.iml, .idea/misc.xml, board/models.py
add product table to models.py
=> Feat: add product table

board/admin.py
admin.py에서 product 테이블이 나올 수 있게 수정함
=> Feat: add Class Product in models.py

gwachaepah_practice/settings.py, secret.py
secret key 와 database 정보를 heroku 환경변수로 저장하여 사용할 수 있도록 수정.
해보고 안되면 다시 수정 예정
=> Feat: modify settings.py to use secret key in heroku config env

board/views.py, templates/main.html
메인페이지에 랜덤하게 데이터를 뽑아내기 위한 코드 작성을 완료
=> Feat: Random Product in Mainpage

gwachaepah_practice/settings.py, requirements.txt
drf를 설치하고, 기본 세팅을 했다.
pagination 기능을 settings.py에 넣었다.
게시물이 10개가 넘어가면 다음 페이지가 생기는 기능이다.
=> Feat: install drf & init setting

board/serializers.py
board 앱에 serializers.py 파일을 만들어 product 모델에 대한 serializer meta class 를 생성함
=> Feat: add meta data in serializer

board/views.py
- mixin 기능이 내장된 generic views를 사용해, `ProductList class`를 만들었다.
- 여기에는 product의 내용이 들어간다.
- drf 튜토리얼에는 `ProductDetail class`도 선언하는데, 이 테이블에서는 이름과 이미지만 보여주기 때문에(read 기능만 수행) 넣지 않았다.
- list를 create하는 것은 api에서 하지 않기 때문에, 인자를 `ListAPIView`로 넣어주었다.
- 현재는 모든 product를 보여준다.
=> Feat: add ProductList class using generic

gwachaepah_practice/urls.py
- urls.py에 product api를 제공하기 위한 `product-api`를 만들어넣었다.
- 또한, `.json`만 치면 json 형식으로 제공되는 코드를 넣어주었다.
=> Feat: add product-api url

board/views.py
- views.py의 ProductList class에서 보여줄 목록을 전체가 아닌 현재 month에서 랜덤으로 4개만 보여지게 필터링했다.
=> Fix: product api list filtering

board/management/commands/del_old_data.py, board/management/commands/put_new_data.py, board/open_api.py
- 일주일 이전의 데이터를 지우기 위한 스케줄러를 생성했다.
- 그리고 사용하지 않는 임포트 구문도 지웠다.
=> Feat: add scheduler for delete old data & delete unused import

board/serializers.py, board/views.py, gwachaepah_practice/urls.py
- 어제 작업한 product-api처럼 post-api도 줄 수 있게 생성하였다.
- urls, views, serializers 파일들에서 api 로 줄 수 있게 작업을 완료하였다.
- 헷갈리지 말 것! 이 api는 post가 아니라 **board에 주로 들어간다.**
=> Feat: add post-api

templates/board.html
- board 페이지에서 댓글이 다시 보일 수 있도록 board.html을 수정하였다
=> Fix: comments in board page are working

board/serializers.py, board/views.py, gwachaepah_practice/urls.py
- search api를 만들었다.
- `views.py`에서 `SearchList` 클래스를 generics를 이용하지 않은 class-based views로 만들었다.
- `?search=[수확물이름]` 하면 그 수확물이름을 포함한 데이터가 api로 잘 제공된다.
=> Feat: add search api

board/forms.py, board/views.py, gwachaepah_practice/urls.py, templates/board.html, templates/new.html
- post를 생성할 수 있는 url과 views에 메서드를 만들었다.
- `new.html`도 생성해서 작성한 게 저장될 수 있도록 했다.
- `new`는 생성하는 페이지가 보이는 기능이고, `create`는 그게 저장되는 기능이다.
=> Feat: create post

board/views.py, gwachaepah_practice/urls.py, templates/board.html, templates/edit.html
- Post CRUD를 위한 작업을 계속 하였다.
- Update 기능과 Delete기능을 구현 완료하였다.
=> Feat: add update and delete post

board/views.py, gwachaepah_practice/urls.py, templates/board.html, templates/show.html
- 기존 board 페이지에서 모든 게시글에 대한 본문, 댓글 등 데이터가 모두 보였는데 이기능을 show.html 을 만들어 분리했다
- board 에서 title 을 누르면 show 페이지로 넘어가고, 해당 페이지에서 해당 id 에 해당하는 본문내용, 댓글이 보이도록하고 수정/삭제 기능이 들어가도록 처리하였다.
=> Feat: add post detail page

board/forms.py, board/views.py, gwachaepah_practice/urls.py, templates/show.html
- comment를 작성할 수 있는 form을 만들고자 했는데, 다 완성시키지 못했다.
- 저장이 안 된다.
=> HOTFIX: create comment not solved

board/forms.py, board/views.py, templates/show.html
- 해결하지 못한 comment create를 해결하였다!!!!! 와ㅏㅏ!!!!
=> Fix: comment create error

board/views.py, gwachaepah_practice/urls.py, templates/show.html
- update를 하기 위해서는 댓글이 존재해야하기 때문에, `show.html`에 content 유무 조건문을 넣어주었다.
- create와는 달리, update와 delete는 `comment_key`가 필요하기 때문에, 인자로 넣어주었다.
=> Feat: update and delete comment

board/serializers.py, board/views.py
- product-api에서 month는 api 안에 줄 필요가 없으므로 제외함
- board-api에서 각 글들이 생성된 순서의 역순으로 보내지게 함
- `format=None` 옵션에 대해 논의 후 코드에서 삭제함
=> Modify: api setting

board/views.py
- `search-api` 에서 검색한 수확물 정보와 함께 board에 있는 포스트들 정보도 같이 볼 수 있게 바꿨다.
=> Feat: add board data in search-api

board/forms.py, board/views.py, gwachaepah_practice/urls.py, templates/board.html, templates/main.html
- 아래 문서를 보면서, default user table에서 미리 저장했던 데이터를 가지고 login & logout 기능을 구현해보았다. [Using the Django authentication system¶
](https://docs.djangoproject.com/en/3.2/topics/auth/default/#django.contrib.auth.login)
- 로그인을 하면 user 정보를 가지고 있지 않기 때문에, `inspect - local storage` 를 확인해보면, user value 이 들어가있지 않는다. -> 사실 여기서 확인하는 것조차 확실하지 않음 🥲
=> Bug: user login & logout

board/views.py, templates/board.html, templates/show.html
- search-api 에서 제공되는 데이터에서 가격정보가 없는 경우를 제거했다
- search-api 를 최근 정보 순으로 오더링했다
- board 페이지와 post 페이지에서 이미지가 너무 크게 보이는 케이스가 있어 사이즈 조정을 했다
=> Modify: search-api filtering & ordering & html img size

board/forms.py, board/views.py
- User가 로그인 되어있다는 가정하에 Post 와 Comments에서 유저데이터를 제대로 받아올 수 있도록 작업하였다.
- 다른 사람(본인이 아닌 사람)이 게시글과 댓글을 수정/삭제 하는 부분에 대해서 고민했지만 아직 이 부분에 대한 가드를 해주지는 않았다.
=> Modify: request user in post & comments

board/views.py
- DELETE는 작동 되는 것 같으나, PUT은 테스트 동작이 되지 않았고, POST는 동작 테스트를 하지 못했다.
- swagger에서 확인할 수 있도록 오토스키마를 달아보았지만, 뭔가 값을 제대로 주고받는 것 같지 않았다.
=> Bug: add Post & PUT & Delete method in post

board/serializers.py, board/views.py, gwachaepah_practice/urls.py
- `PostList`에서는 포스트 하나만 다루게 바꿨다. Post 조회, 수정, 삭제가 가능하다.
- `BoardList`에서 Post를 생성할 수 있게 했다.
- `CommentDetailList`에서 댓글 하나만 다루게 바꿨다.
- `CommentList`에서는 해당 포스트의 모든 댓글들을 조회하고 새 댓글을 생성할 수 있다.
- `Serializer`에서 `DateTimeField`의 형식을 바꿨는데, 그게 에러를 발생시켜서 모델의 필드에서 바꿔야 한다.
- Swagger에서 `POST`나 `PUT`을 하려면 어떤 내용을 입력해줘야 하는데, 그 form이 보이지 않아서 찾아보다가 `generic`으로 바꾸라는 글을 봐서 `generic`으로 바꿨다.
- `generic`으로 바꾸는 과정에서 기존에는 `GenericAPIView`를 사용했었는데, `RetrieveUpdateDestroyAPIView`로 바꿨다. 그래서 코드가 두 줄로 굉장히 짧아졌다.
=> Bug: cannot POST or PUT in Swagger & image POST error

board/views.py
- `PUT` 은 해당 object 의 전체 필드에 대해서 들어온 값으로 바뀐다는 문제가 있어서, `PATCH`처럼 동작하게 만들어봤다.
- `generics.RetrieveUpdateDestroyAPIView` 에서 결국 `UpdateModelMixin` 를 사용한다. 그리고 그 안에 `update()` 가 있는데, 거기서 `partial = kwargs.pop('partial', False)` 이 부분을 `True`로 바꿔서 부분적 수정이 가능하게 했다.
=> Modify: PUT to PATCH api

board/forms.py, board/models.py, board/views.py, gwachaepah_practice/urls.py, templates/main.html, templates/user_register.html
- 회원 가입 페이지로 이동해서 회원가입 진행
- 정상적으로 회원가입되면 username, password 는 models.auth 의 User 테이블에 저장된다
- 동시에 Profile 테이블에 User 와 One to One 으로 연결된 데이터가 생성되고 local 데이터도 저장된다
-
=> Feat: add user register automatically add profile data

gwachaepah_practice/settings.py
- 프론트에서 api를 받아오는 과정에서 CORS 에러에 직면했다.
- django에서 enable CORS를 하는 과정이 있어 따라해보았다. -> [Django CORS Guide: What It Is and How to Enable It](https://www.stackhawk.com/blog/django-cors-guide/ )
- 이 코드가 제대로 동작하는지는 프론트에서 확인해보아야 한다.
=> Feat: add CORS

board/views.py
- 현재 user key 가 있어야 새글 작성이 가능하다
- 프론트에서 테스트하기에 userkey 가 없어서 400 에러만 나오는 상황
- 임의의 username 이 들어왔을 때 랜덤한 userkey 를 받아서 새글 작성이 가능하도록 수정해보았다
=> Feat: for front random user can create post

board/views.py, gwachaepah_practice/urls.py
- comment-api에서 PATCH를 PUT에서도 동작할 수 있게 수정을 시도했다.
- swagger에서 post-api와 comment-api PUT에서 image field가 보이지 않았다.
- PostList에서 `parser_classes = (MultiPartParser,)`를 추가했더니 image field가 보이기는 한다. 하지만 추가적인 수정이 필요해보인다.
=> Modify: PostList to show image field

gwachaepah_practice/settings.py, requirements.txt
- 지난번 CORS 셋팅했을 때 에러가 나서 다시 원상복구 하였다
- 다시 확인해보니 빼먹은 부분이 많았던 것 같아서 다시 시도해본다
- 이 부분은 프론트에서만 문제가 생기는 것으로 일단 deploy 해보고 해결 여부를 확인하고자 한다
=> Modify: test CORS setting

board/serializers.py, board/views.py, gwachaepah_practice/urls.py
- 회원가입 시 중복 아이디 방지를 위한 api를 만들었다.
- 중복 아이디가 없을 경우 202, 중복 아이디가 있는 경우 401로 리턴한다.
=> Feat: user check for register

board/serializers.py, board/views.py, gwachaepah_practice/settings.py, gwachaepah_practice/urls.py
- `api/token/verify/`: django에 내장된 `TokenVerifyView`를 이용해 클라이언트에서 request하는 access token이 유효한지 여부 판단하는 api
- 로그인 성공시, 처음 access token과 refresh token을 response할 때, 그 token에 해당 username(user의 id)과 local(지역) 정보를 포함하도록 `api/token/`에 수정하였다.
- `api/token/verify` 에서 access token이 유효하다면 아래 사진처럼 200을 반환한다
- 만약, 유효하지 않다면 401 에러를 반환한다
=> Feat: add user api GET

board/serializers.py
- 사용자가 로그인을 시도하면, 로그인 정보가 맞는지 확인한 뒤 신호를 보내줘야한다.
- 로그인 정보가 잘못된 경우(입력된 username 과 password 에 맞는 사용자가 없는 경우) -> 401 에러코드
- 로그인 정보가 알맞는 경우 -> 200 성공 코드 와 함께 data 에 두개의 토근 + 유저정보를 보내준다
=> Modify: response user info with tokens when user try login

gwachaepah_practice/urls.py
- 일관성과 가독성, 통일성을 위해 전반적으로 api url 이름을 변경해보았다.
```
[받아야 할 것]/api/[구체적]/(pk)
```
=> Change: api urls

board/views.py, gwachaepah_practice/urls.py
- `views.py` 에 있는 클래스들 이름을 보다 직관적으로 알 수 있게 바꿨다.
- 그리고 `views.py` 와 `urls.py` 에 있는 `import` 구문들을 정리했다.
=> Change: class name in views & organize import

board/serializers.py, board/views.py, gwachaepah_practice/urls.py, templates/board.html
- username 과 password, region 이 회원가입되도록 요청 들어오면 User 테이블에 추가한다.
- front 는 사용자가 입력한 값을 아래와 같은 폼의 data로 보내야한다
- 정상적으로 User 에 데이터가 추가되면 201 성공 코드를 보내준다.
=> Feat: user register api

board/permissions.py, board/views.py, gwachaepah_practice/settings.py
- api 접근 권한을 설정하기 위해 [Object level permissions](https://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#object-level-permissions) 을 시도해보았다
=> Feat: add object level permissions

board/serializers.py
- comment에서 username 대신 `pk`가 보여, post와 동일하게 username을 넣어주었다.
=> Feat: add username in comment

board/views.py
- post에 들어가면 `view_count`가 올라가야 하는데, 백엔드가 테스트 용도로 사용한 html에서만 올라갈 수 있게 해놓고 api로 보내는 작업은 하지 않아서 수정했다.
=> Fix: view_count

board/views.py
- @deftones88 님이 search api값에 에러가 있다는 제보를 하였고, 이전처럼 필터된 값을 받아 이를 시리얼라이즈 하는 방식으로 수정해주었다.
=> Fix: Search api Error fix

board/views.py
- #139 의 `get_permissions` 함수가 다른 api에서도 사용되기 때문에 `set_permissions`의 함수로 분리했다.
=> Modify: put get_permissions in all apis

board/serializers.py, board/views.py, gwachaepah_practice/urls.py
- 현재 서울특별시 내에 위치한 동을 기준으로 `region api` 만들었다.
- 동을 입력하면, 서울특별시 내에 위치한 모든 해당 동을 필터링해 시/구/동/코드 를 전부 보내준다.
=> Feat: add region api

board/serializers.py, board/views.py
- 로그인한 유저의 지역 정보를 받아서 게시판에 보내줄 데이터를 필터링했다.
- 시/군/구 로 필터링했다.
- 각 게시물 작성자의 지역정보를 나타낼 수 있게 `city` 와 `address` 정보를 보내주었다.
=> Feat: filter region in board api

board/serializers.py
- @deftones88 가 post에는 주소가 안보인다고해서 `city`와 `address`를 넣어주었다.
=> Feat: add region in post api
