gwachaepah_practice/settings.py
헤로쿠 서버에서 config var 에 cloudinary storage 관련 secret 정보 환경변수로 넣고
settings.py 에서는 해당 정보 환경변수에서 불러올수 있게 수정했습니다.
확인 부탁드려요
=> Fix: hide cloudinary secret info in settings.py by use heroku config var

board/serializers.py, board/views.py, gwachaepah_practice/urls.py
- board 페이지에서 필요로 하는 데이터만 추린 api 를 생성
- board 페이지에 보낼 데이터이므로 이름을 board-api 로 지정
- 기존의 post-api 와 기능이 겹치고, post-api 가 수정될 예정이므로 post-api 에서 일부 수정하는 방향으로 진행했다.
- 관련된 views.py 와 urls.py 도 수정함
=> Modify: modify post_api to board_api

board/views.py
- comment data를 동적으로 가져오기 위해, generic을 사용하지 않았다.
- comment serializer에 하나의 포스트와 그 포스트 id에 상응하는 댓글들을 넣었다.
- generic을 사용한 board-api와 사용하지 않은 commet-api를 비교해보면, 보여지는 json 구조가 다르게 보이는 것을 알 수 있다.
=> Feat: get comment data dynamically

board/serializers.py, board/views.py, gwachaepah_practice/urls.py
- post 상세보기에서 필요한 api를 제공해야 하는데, 해당 post와 그 포스트에 종속되는 comment를 한번에 보내주기로 했다. #62 
- post와 comment가 각자 다른 모델에 들어가 있는 게 문제였다.
- 첫 번째 방법: `django-rest-multiple-models`를 설치해서, `ObjectMultipleModelAPIView`로 사용해보려고 했다. 그런데 이것도 generics base여서 pk를 가져올 수 없었다. -> 포기
- 최종: multiple queryset을 json으로 serialize 하는 방법을 찾아봤다. -> 성공
=> Feat: merge post and comment in post-api

board/views.py, gwachaepah_practice/urls.py
- search-api의 결과 값을 swagger에서 잘 확인할 수 있게 parameter를 잘 넣어주었다.
=> Modify: search api in url

gwachaepah_practice/settings.py
- 프론트와의 이야기를 통해 page-size를 10에서 12로 조정함
- 다른 api (ex. comment)의 경우, 페이지가 작동하지 않는 이유는 일반 APIview를 써서 그렇다.
=> Modify: api page size change

board/views.py, gwachaepah_practice/urls.py
- `search-api` 에서 검색어를 querystring 으로 받도록 처리함
- 초기엔 이 방법을 사용했을 때 `swagger` 에서 param 입력이 안되는 문제가 있었다
- `swagger_auto_schema` 를 이용해서 `swagger` 에서도 search 파라미터를 입력하여 api 를 받을 수 있도록 수정하였다.
=> Fix: show search param in swagger using querystring

board/views.py, gwachaepah_practice/urls.py
- 프론트 @deftones88 의 요청으로 `search-api`를 이전처럼 검색한 수확물 정보만 보내지게 바꿨다.
- 역시 프론트 @deftones88 의 요청으로 `board-api`에서 검색한 내용과 태그에 따라 분류해서 보냈다.
=> Modify: board-api filtering & revert search-api

board/serializers.py
- `CommentSerializer`, `PostDetailSeriaiizer` 에서 DateTimeField로 날짜 포맷을 바꾸니, api에서 `POST`하면 시간이 자동으로 생성되지 않아 에러가 났다.
- model이나 form을 바꿔주는 경우도 생각했지만, 일단 프론트에서 가공하는걸로 결정이 났다.
=> Delete: DateTimeField in serializer

board/views.py
- POST 타입으로 HTTP 를 통해 프론트에서 들어오는 request 에는 method = "post" 와 data = {항목들} 이 json 으로 들어와야한다.
- 일단 board-api 에서 post 부분에는 data 를 받을 수 없는 상태이다.
- 그래서 comment-api 의 post 부분에서 data 가 어떻게 들어와야하고, 그 data 를 어떻게 다뤄야하는지 테스트해보았다.
- 우선 comment-api 에서 post 될 때에는 comment 내용과, comment 가 달릴 post_key, 그리고 comment 를 작성한 user_key 가 들어온다
- 이 세 데이터는 dict 타입으로 오기때문에 user_key의 value 를 받으려면 request.data["user_key"] 형식으로 가져와야한다. (request.data.user_key 로 가져오려다가 에러남)
- 이 때, post_key 와 user_key 는 int 타입으로 pk 에 해당한다
- User 테이블에서 username 이 곧 pk 역할을 하는 것으로 알았는데, pk 는 int 타입이고, username 은 str 타입이다.
- 따라서 data 에 들어온 user_key 에 해당하는 User object 가 있는지 확인하려면 User.objects.get(pk=user_key_value) 로 찾아야한다.
- try 를 통해 data 에 들어온 user_key 에 해당하는 User 가 존재하는지 확인하고, 존재한다면 그 값을 그대로 두고 존재하지 않는 경우 User 테이블에 있는 항목들 중에서 임의의 key 를 가져와 …
=> Ylee random user create post and comment

board/models.py, board/views.py, gwachaepah_practice/settings.py, gwachaepah_practice/urls.py
- 이전에는 board-api 를 검색어, 태그에 따라서 필터링 될 수 있게 query string 을 받을 수 있는 형태로 만들었다.
- 이 떄 api url 이 `~/board-api` 인데, 뒤에 `/` 가 없어서 전체 데이터 GET 기능과 pagination 이 안되는 문제가 발생했다(GET 기능은 프론트가 로컬에서 테스트할 때 발생한 문제. swagger 나 api url 에서는 문제가 없었다. 원인을 아직 확실히 모르는 상태임)
- 이를 위해 `~/board-api?querystring` 형태의 api 와 `~/board-api/` 형태의 api 를 분리하기로 했다
- 동시에 view 타입도 generic 으로 변경했다
- `~/board-api` url 은 board 페이지에 검색어와 태그에 따라 필터링되는 보드 데이터를 GET 하는 기능을 하고, (class : BoardSearchList)
- `~/board-api/` url 은 board 페이지에 띄워질 전체 보드 데이터 GET 기능과, 새 게시글을 작성하는 POST 기능을 한다(class : BoardList)
- BoardList 함수에서 `def post` 함수는 현재 프론트에서 유저키를 임의로 넣어도 작동하도록 하기 위해서 넣은 함수로, 후에 삭제한다.
- swagger 에서 파일 업로드가 안되는 문제를 발견해서 MultiPartParser 를 추가했다.
=> Modify: devide board-api by role

board/views.py
- `views.py`의 `PostList`와 `CommentList`에 put을 fetch처럼 쓸 수 있는 update func 를 다시 올렸다.
- `BoardSearchList`에 오류가 있어 `queryset`과 `serializer_class`를 다시 설정해주었다.
=> Modify: resetting update func in post-api & comment-api

board/views.py
- `CommentDetailList`에 `MultiPartParser`를 넣어주었다
- `PostList`에는 `MultiPartParser`가 이전에도 있었기 때문에 따로 넣어주지는 않았고, 프론트에 관련 부분 코드 수정을 요청하였다.
=> Modify: add MultiPartParser into CommentDetailList & PostList

board/views.py
- 프론트에서 테스트를 할 때 board 페이지에서 post들이 정렬되어 나타나지 않는다.
- 최근에 게시된 글이 가장 먼저 나타나게(맨 앞에) 정렬했다.
=> Modify: ordering post in board

board/views.py
- `PUT`을 `PATCH`처럼 쓰고 있었는데, 멘토링에서 그렇게 쓰는 것은 의미가 없다고 했다.
- 되돌려놓기 위해 `PUT`에서 부분적으로 수정할 수 있는 함수인 `update()`를 오버라이딩 헤서 작성했던 부분을 뺐다.
=> Fix: delete update function in PUT

board/serializers.py
- `serializers.py`에서 `read_only_fields`를 추가했다.
- `fields`에 있는 정보들 중 `GET`할 때 말고는 필요없는 정보들을 `read_only_fields`에 넣으면 속도가 빨라진다.
- `read_only_fields`에 있는 정보들은 swagger에서 `PUT`이나 `PATCH`를 할 때 나타나지 않는다.
=> Feat: add read_only_fields in serializer

board/serializers.py, board/views.py, gwachaepah_practice/urls.py
- board-api POST에서 500 에러가 뜨는 현상이 있었다.
- POST 할 때는, `read_only_fields` 가 필요하지 않으므로 기존 `PostSerializer`와 `CommentSerializer`에서 POST 하는 기능만 따로 serializer를 만들어 주었다.
- 나눠진 serializer에 따라 views.py에서도 POST 하는 함수만 따로 만들어 주었는데, post-api POST에는 이미지가 들어가므로 `parser_classes = (MultiPartParser,)` 를 추가하였다.
- 기존에는 board-api에 post를 POST 하는 기능이 있었는데, 연관성과 통일성을 위해 `post-api/` 로 바꾸었다.
=> Fix: divide serializer for POST

board/views.py, gwachaepah_practice/urls.py
- @deftones88 의 요청: 하나의 post에 있는 comment들 불러오는 api 필요하다.
- post 하나와 그에 대한 comment들을 보내주는 api를 post 없이 해당 post의 comment들만 보내주는 api로 변경했다.
- 나중에 바꾸겠지만, 일관성과 통일성과 가독성을 위해 api 관련 url을 바꿨다. -> '[뭔지]/api/[구체적]/'
=> Modify: divide comment list and detail

board/views.py
- 보드 페이지에서 검색어가 들어오거나 소분/나눔/완료 태그별로 필터링될 때의 수정 (~board/api url)
- 검색어만 들어온 경우 완료(tag=2) 를 제외하고 보여지도록 한다
- 검색 또는 태그 필터링이 되는 경우에도 페이지네이션 되도록 한다
=> Modify: board search case exclude tag=2, include pagination

board/views.py
- #123 에서 serializers를 줄이는 과정에서 `from .`을 붙이지 않아, 프론트에서 `ModuleNotFoundError`가 떠서, 수정했다.
=> Fix: import serializers from .

board/serializers.py, board/views.py, gwachaepah_practice/urls.py
- 게시판 페이지에서 post 별로 작성자 정보를 user_key 로 받는데, 이 때 int 형의 pk 만 response 되어서 프론트에서 username 을 출력할 수 없었다.
- BoardSerializer 와 PostSerializer 를 수정하여 post obj 마다 user_key 에 해당하는 username 도 str 타입으로 추가로 보내주기로 함.
- board 페이지와 post 페이지에서 댓글 수 정보도 띄우고싶다고 요청하여 위와 같은 방법으로 comment_cnt 필드도 추가하여 response 하기로 하였다
=> Modify: add comment cnt and username data when post get request

board/models.py
- 프론트의 작업을 위해 `blank=True, null=True`였던 Post의 ImageField를 다시 필수로 지정하기 위한 작업을 하였습니다
=> Fix: return ImageField in Post model

board/views.py
- `무` 로 검색했을 때 `당근 - 무세척` 이 나오는 케이스 발견
- space 만 넣어 검색했을 때 `흰 콩`등 space 가 추가되어있는 모든 데이터가 출력된다
- 품목에 검색어와 동일한 데이터가 있는 경우에는 해당 데이터를 response 하고, 품목에 검색어와 동일한 케이스가 없는 경우에만 품종에서 추가로 검색하는 방법으로 필터링한다.
- 검색어가 한글/영문이 아닌경우를 필터링하여 해당 케이스에는 빈 데이터가 response 되도록 한다
- 검색어 중 'g' 가 있는 경우 품종에 '100g' 등의 unit 정보가 있는 경우에도 검색되는 케이스가 발견되었다.
- 검색어에 'g' 가 포함된 경우에도 빈 데이터가 response 되도록 셋팅하였다
=> Modify: add more filter condition in search price list

board/models.py, board/views.py
- 기존에는 User table과 Profile table를 연결하는데, signal을 사용했었다.
- '의도를 명확하게 드러내라'는 멘토님의 조언으로 `UserRegisterView` 에서 해당 함수를 가져다 쓰는 것을 시도했다.
- `set_profile`이라는 함수를 만들어, 기존의 User 에서 Profile object를 생성하고, 그 object에 region을 넣어주는 방법으로 진행하였다.
=> Modify: add set_profile and remove signal in models

gwachaepah_practice/settings.py
- api에 아무나 접근하지 못하게 하기 위해서, CORS 설정을 바꿨다.
- 모든 사람이 접근할 수 있는 `CORS_ORIGIN_ALLOW_ALL = True`에서 프론트와 백엔드 로컬 주소, heroku 주소 총 4개만을 추가했다.
=> Modify: CORS settings

board/views.py, gwachaepah_practice/settings.py, gwachaepah_practice/urls.py
- api에 url로 직접 접속했을 때, 관리자가 아니면 볼 수 없게 했다.
- root 계정으로 로그인해야 `GET`, `POST`, `PUT`, `DELETE` 등이 가능하다.
- 여기서는 JWT로 로그인하지 않고, Session으로 로그인하기 때문에 Session을 `DEFAULT_AUTHENTICATION_CLASSES`에 추가해야 했다.
=> Feat: add api authentication setting

board/views.py
- request header 에 referer 가 없는 경우 403 에러를 보낸다 (브라우저에 직접 api url 를 입력한 경우)
- 프론트 서버, swagger, 로컬 swagger 에서 request 를 보낸 경우에만 데이터를 보내고 그 외에는 418 에러를 보내도록 셋팅하였다
=> Modify: add allow request url

board/views.py
- 브라우저에 api url 을 입력한 경우에도 에러가 아닌 스태프 권한 로그인이 된 경우에만 데이터를 볼 수 있도록 셋팅을 바꾸었다.
- url 에 대한 permission_classes 를 셋팅하는데, request 에 referer 가 있는지 확인하고, 없는 경우(브라우저에서 직접 입력하여 접근) 스태프 로그인이 된 경우에만 데이터 볼 수 있도록 조건문 처리하였다
- referer 가 있는 경우에도 프론트에서 요청한 경우가 아니라면 스태프 권한으로 로그인 된 경우에만 데이터를 볼 수 있도록 셋팅하였다
- referer 가 프론트 서버와 같은 경우에는 allowany 로 셋팅하고, 그 외의 경우에는 스태프 권한 확인하도록 하였다.
=> Modify: set custom permission classes in several cases

gwachaepah_practice/settings.py
- swagger 에서 django login 버튼을 눌렀을 때 에러가 발생한다.
- swagger 기본 셋팅으로 django login 버튼을 누르면 ~/accounts/login/ 으로 이동하여 장고 로그인을 수행하는데
- 장고와 yasg 둘 중 어디의 문제인지 모르겠지만 우리는 drf 를 쓰고있으므로 drf 로그인을 하려면 ~/api-auth/login/으로 이동해야한다.
- 이를 위해서 settings.py 에 swagger_setting 을 추가하여 기본값을 변경하였다.
- 이후 테스트에서 브라우저에 url 넣은 경우와 swagger 에서 테스트하는 경우 모두 동일하게 동작하는 것을 확인했다.
=> Feat: django login/out in swagger
